<?php


$c_name = $this->request->getPost('c_name');
$id = $this->request->getPost('id');


?>
<style>
    body {
        margin-top: 20px;
        background-color: #f7f7fc;
    }

    .timeline {
        list-style-type: none;
        position: relative
    }

    .timeline:before {
        background: #dee2e6;
        left: 9px;
        width: 2px;
        height: 100%
    }

    .timeline-item:before,
    .timeline:before {
        content: " ";
        display: inline-block;
        position: absolute;
        z-index: 1
    }

    .timeline-item:before {
        background: #fff;
        border-radius: 50%;
        border: 3px solid #3b7ddd;
        left: 0;
        width: 20px;
        height: 20px
    }

    .card {
        margin-bottom: 24px;
        box-shadow: 0 0 0.875rem 0 rgba(33, 37, 41, .05);
    }

    .card {
        position: relative;
        display: flex;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-color: #fff;
        background-clip: initial;
        border: 0 solid transparent;
        border-radius: .25rem;
    }

    .card-body {
        flex: 1 1 auto;
        padding: 1.25rem;
    }

    .card-header:first-child {
        border-radius: .25rem .25rem 0 0;
    }

    .card-header {
        border-bottom-width: 1px;
    }

    .pb-0 {
        padding-bottom: 0 !important;
    }

    .card-header {
        padding: 1rem 1.25rem;
        margin-bottom: 0;
        background-color: #fff;
        border-bottom: 0 solid transparent;
    }
</style>

<div class="container">
    <div class="container-fluid p-0">
        <h1 class="h3 mb-3"><?php print_r($c_name) ?></h1>
        <div class="row">
            <div class="col-xl-8">
                <div class="card">
                    <div class="card-header pb-0">
                        <div class="card-actions float-right">
                            <div class="dropdown show">
                                <a href="#" data-toggle="dropdown" data-display="static">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal align-middle">
                                        <circle cx="12" cy="12" r="1"></circle>
                                        <circle cx="19" cy="12" r="1"></circle>
                                        <circle cx="5" cy="12" r="1"></circle>
                                    </svg>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="card-body">
                        <table class="table table-striped" style="width:100%">
                            <thead>
                                <tr>

                                    <th>Name</th>
                                    <th>button</th>

                                </tr>
                            </thead>
                            <tbody>
                            <!-- Current weather
Forecast
History
Time Zone
Sports
Astronomy
Weather Alerts
Air Quality -->
                                <tr>
                                    <td>Current weather</td>
                                    <td>
                                        <form action="/index/currentWeather" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="current_weather" value="current_weather" class="btn btn-primary"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Forecast</td>
                                    <td>
                                        <form action="/index/forecast" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Forecast" value="Forecast" class="btn btn-secondary"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>History</td>
                                    <td>
                                        <form action="/index/history" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="History" value="History" class="btn btn-success"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Time Zone</td>
                                    <td>
                                        <form action="/index/timeZone" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Time_Zone" value="Time_Zone" class="btn btn-danger"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Sports</td>
                                    <td>
                                        <form action="/index/sports" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Sports" value="Sports" class="btn btn-warning"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Astronomy</td>
                                    <td>
                                        <form action="/index/astronomy" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Astronomy" value="Astronomy" class="btn btn-info"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Weather Alerts</td>
                                    <td>
                                        <form action="/index/weatherAlerts" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Weather_Alerts" value="Weather_Alerts" class="btn btn-dark"></td>
                                    </form>
                                    </td>
                                </tr>

                                <tr>
                                    <td>Air Quality</td>
                                    <td>
                                        <form action="/index/airQuality" method="post">
                                            <input type="hidden" name="c_name" value="<?php if (isset($c_name)) {
                                                                                            print_r($c_name);
                                                                                        } ?>">
                                            <input type="hidden" name="id" value="<?php if (isset($id)) {
                                                                                        print_r($vid);
                                                                                    } ?>">
                                    <td><input type="submit" name="Air_Quality" value="Air_Quality" class="btn btn-primary"></td>
                                    </form>
                                    </td>
                                </tr>

                              

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>


        </div>

    </div>
</div>