<?php

// echo "<pre>";
// print_r($current_var);
// echo "</pre>";


?>


<style>
    body{margin-top:20px;
background-color: #f7f7fc;
}

.timeline {
    list-style-type: none;
    position: relative
}

.timeline:before {
    background: #dee2e6;
    left: 9px;
    width: 2px;
    height: 100%
}

.timeline-item:before,
.timeline:before {
    content: " ";
    display: inline-block;
    position: absolute;
    z-index: 1
}

.timeline-item:before {
    background: #fff;
    border-radius: 50%;
    border: 3px solid #3b7ddd;
    left: 0;
    width: 20px;
    height: 20px
}
.card {
    margin-bottom: 24px;
    box-shadow: 0 0 0.875rem 0 rgba(33,37,41,.05);
}
.card {
    position: relative;
    display: flex;
    flex-direction: column;
    min-width: 0;
    word-wrap: break-word;
    background-color: #fff;
    background-clip: initial;
    border: 0 solid transparent;
    border-radius: .25rem;
}
.card-body {
    flex: 1 1 auto;
    padding: 1.25rem;
}
.card-header:first-child {
    border-radius: .25rem .25rem 0 0; public function currentWeatherAction() {
        $url = $this->request->get('c_name');
        $len = strlen($url);
        for ($i = 0; $i < $len; $i++) {
            if ($url[$i] == ' ') {
                $url[$i] = '+';
            }
        }

        $current = 'http://api.weatherapi.com/v1/current.json?key=0bab7dd1bacc418689b143833220304&q='.$url.'&aqi=yes';


       
        $client = new Client([
            'base_uri' => $current,
        ]);
          
        
        $response = $client->request('GET');
          
          
        $body = $response->getBody();
        $arr_body = json_decode($body,true);

        echo "<pre>";
        print_r($arr_body);
       // die;
        $this->view->current_weather = $arr_body;
    }
}
.card-header {
    border-bottom-width: 1px;
}
.pb-0 {
    padding-bottom: 0!important;
}
.card-header {
    padding: 1rem 1.25rem;
    margin-bottom: 0;
    background-color: #fff;
    border-bottom: 0 solid transparent;
}
    </style>

<div class="container">
    <div class="container-fluid p-0">
		<h1 class="h3 mb-3"><?php print_r($current_var[0]['country'])?></h1>
		<div class="row">
			<div class="col-xl-8">
				<div class="card">
					<div class="card-header pb-0">
						<div class="card-actions float-right">
							<div class="dropdown show">
								<a href="#" data-toggle="dropdown" data-display="static">
									<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-more-horizontal align-middle"><circle cx="12" cy="12" r="1"></circle><circle cx="19" cy="12" r="1"></circle><circle cx="5" cy="12" r="1"></circle></svg>
								</a>

								<div class="dropdown-menu dropdown-menu-right">
									<a class="dropdown-item" href="#">Action</a>
									<a class="dropdown-item" href="#">Another action</a>
									<a class="dropdown-item" href="#">Something else here</a>
								</div>
							</div>
						</div>
					
					</div>
					<div class="card-body">
						<table class="table table-striped" style="width:100%">
							<thead>
								<tr>
									
									<th>Name</th>
									<th>Region</th>
									<th>latitude</th>
									<th>longitude</th>
                                    <th>Detail</th>
								</tr>
							</thead>
							<tbody>
                                <?php 
                                foreach($current_var as $k => $v)
                                {
                                
                                   
                                ?>
                                <form action="/index/particularCity" method="post">
								<tr>	
                                							
									<td><?php if(isset($v['name'])){ print_r($v['name']);} ?></td>
									<td><?php if(isset($v['region'])){ print_r($v['region']);} ?></td>
									<td><?php if(isset($v['lat'])){ print_r($v['lat']);} ?></td>
									<td><?php if(isset($v['lon'])){ print_r($v['lon']);} ?></td>
                                    <input type="hidden" name="c_name" value="<?php if(isset($v['name'])){ print_r($v['name']);} ?>">
                                    <input type="hidden" name="id" value="<?php if(isset($v['id'])){ print_r($v['id']);} ?>">
                                    <td><input type = "submit" value = "submit" class="btn btn-primary"></td>
								</tr>
                                </form>
                                <?php

                                    }
                                    ?>
								
							</tbody>
						</table>
					</div>
				</div>
			</div>

			
		</div>

	</div>
</div>

